/** @type {import('tailwindcss').Config} */
const path = require('path')

module.exports = {
  content: [
    path.join(process.cwd(), './src/**/*.{js,ts,jsx,tsx,mdx}'),
  ],
  theme: {
    extend: {
      colors: {
        background: '#fbfbe2',
        primary: '#a20000',
        primaryContainer: '#d00000',
        onPrimary: '#ffffff',
        onPrimaryFixed: '#410000',
        onPrimaryContainer: '#ffded9',
        onPrimaryFixedVariant: '#930000',
        surface: '#fbfbe2',
        surfaceDim: '#dbdcc3',
        surfaceBright: '#fbfbe2',
        surfaceContainerLowest: '#ffffff',
        surfaceContainerLow: '#f5f5dc',
        surfaceContainer: '#efefd7',
        surfaceContainerHigh: '#eaead1',
        surfaceContainerHighest: '#e4e4cc',
        surfaceTint: '#c00000',
        surfaceVariant: '#e4e4cc',
        onSurface: '#1b1d0e',
        onSurfaceVariant: '#5e3f3a',
        secondary: '#5f5e5e',
        secondaryContainer: '#e4e2e1',
        onSecondary: '#ffffff',
        onSecondaryFixed: '#1b1c1c',
        onSecondaryFixedVariant: '#474747',
        tertiary: '#4e4f4f',
        tertiaryContainer: '#666767',
        onTertiary: '#ffffff',
        onTertiaryFixed: '#1a1c1c',
        onTertiaryFixedVariant: '#464747',
        onTertiaryContainer: '#e6e6e6',
        tertiaryFixed: '#e3e2e2',
        tertiaryFixedDim: '#c6c6c6',
        error: '#ba1a1a',
        errorContainer: '#ffdad6',
        onError: '#ffffff',
        onErrorContainer: '#93000a',
        inversePrimary: '#ffb4a8',
        inverseSurface: '#303221',
        inverseOnSurface: '#f2f2d9',
        outline: '#936e69',
        outlineVariant: '#e8bdb6',
      },
      spacing: {
        xs: '4px',
        unit: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'stack-heavy': '48px',
      },
      fontFamily: {
        'headline-xl': ['Epilogue', 'sans-serif'],
        'headline-lg': ['Epilogue', 'sans-serif'],
        'headline-md': ['Epilogue', 'sans-serif'],
        'label-bold': ['Space Grotesk', 'sans-serif'],
        'label-mono': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': [
          '48px',
          { lineHeight: '1.0', letterSpacing: '-0.04em', fontWeight: '900' },
        ],
        'label-bold': [
          '14px',
          { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '700' },
        ],
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '500' }],
        'headline-lg': [
          '32px',
          { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' },
        ],
        'label-mono': ['12px', { lineHeight: '1.0', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '0px',
      },
    },
  },
  plugins: [],
}
