/** @type {import('tailwindcss').Config} */
const path = require('path')

module.exports = {
  content: [
    path.join(process.cwd(), './src/**/*.{js,ts,jsx,tsx,mdx}'),
  ],
  theme: {
    extend: {
      colors: {
        background: '#fbfbe2',
        primary: '#a20000',
        'primary-container': '#d00000',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#410000',
        'on-primary-container': '#ffded9',
        'on-primary-fixed-variant': '#930000',
        surface: '#fbfbe2',
        'surface-dim': '#dbdcc3',
        'surface-bright': '#fbfbe2',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f5dc',
        'surface-container': '#efefd7',
        'surface-container-high': '#eaead1',
        'surface-container-highest': '#e4e4cc',
        'surface-tint': '#c00000',
        'surface-variant': '#e4e4cc',
        'on-surface': '#1b1d0e',
        'on-surface-variant': '#5e3f3a',
        secondary: '#5f5e5e',
        'secondary-container': '#e4e2e1',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#1b1c1c',
        'on-secondary-fixed-variant': '#474747',
        tertiary: '#4e4f4f',
        'tertiary-container': '#666767',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#464747',
        'on-tertiary-container': '#e6e6e6',
        'tertiary-fixed': '#e3e2e2',
        'tertiary-fixed-dim': '#c6c6c6',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-primary': '#ffb4a8',
        'inverse-surface': '#303221',
        'inverse-on-surface': '#f2f2d9',
        outline: '#936e69',
        'outline-variant': '#e8bdb6',
      },
      spacing: {
        xs: '4px',
        unit: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'stack-heavy': '48px',
      },
      fontFamily: {
        'headline-xl': ['Epilogue', 'sans-serif'],
        'headline-lg': ['Epilogue', 'sans-serif'],
        'headline-md': ['Epilogue', 'sans-serif'],
        'label-bold': ['Space Grotesk', 'sans-serif'],
        'label-mono': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': [
          '48px',
          { lineHeight: '1.0', letterSpacing: '-0.04em', fontWeight: '900' },
        ],
        'label-bold': [
          '14px',
          { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '700' },
        ],
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '500' }],
        'headline-lg': [
          '32px',
          { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' },
        ],
        'label-mono': ['12px', { lineHeight: '1.0', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '0px',
      },
    },
  },
  plugins: [],
}
